const SUCCESS = 200
const CREATED = 201
const EMPTY = 204
const NOT_MODIFIED = 304
const AUTH_ERROR = 401
const CONFLICT = 409
const DATA_ERROR = 422
const SERVER_ERROR = 500

export { SUCCESS, CREATED, EMPTY, NOT_MODIFIED, AUTH_ERROR, CONFLICT, DATA_ERROR, SERVER_ERROR }
